### ISSUE TITLE
Cannot fetch Transaction

### ISSUE THREAD

**Issue by balogatt** [paylike/plugin-virtuemart#13]
Hi!

After the make order I get the folowing alert
<img width="455" alt="screen 2020-09-27 - 12 22 10" src="https://user-images.githubusercontent.com/55018353/94418420-ad030f80-0181-11eb-82ca-0d217d6eee20.png">

I use Test or LIve account the state of order not changed. The money will be deducted from the starter card.

I use:
Joomla! 3.9.21 
VirtueMart 3.8.4 10335

It worked until two weeks ago, I reinstall the plugin, its not help for me.

**Comment by ionutcalara** [comment]
Hi @balogatt, make sure that you are using the correct public key and app key. Make sure that you are using the keys from the same account, and not mixing the test public key with the live app key, or anything of that sort. You can see which is which here: https://paylike.io/img/plugin-steps/fashion-outlet-paylike-create-account.jpg
Please insert your keys again and let me know if you still have issues. 

Remember this is a public forum, so do not share your keys here.

**Comment by balogatt** [comment]
Hi @ionutcalara, The keys are correct, the money arrive, but the order state dosent change, this stay pending.

**Comment by balogatt** [comment]
OK.
I rewoked old test Apps, and try again, Its work now. Thanks

**Comment by ionutcalara** [comment]
Ok, glad to see this is working. I will close the ticket. If you have any other issues, feel free to open a new one.
